use std::env;
use std::fs;
use std::path::PathBuf;

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let maps_dir = manifest_dir.join("../content/maps");
    let out_path = manifest_dir.join("src/maps_embedded.rs");

    let mut entries: Vec<(String, PathBuf)> = fs::read_dir(&maps_dir)
        .unwrap_or_else(|error| panic!("Failed to read {}: {error}", maps_dir.display()))
        .filter_map(|entry| entry.ok())
        .map(|entry| entry.path())
        .filter(|path| {
            path.file_name()
                .and_then(|name| name.to_str())
                .is_some_and(|name| name.ends_with(".map.json"))
        })
        .map(|path| {
            let file_name = path.file_stem().unwrap().to_string_lossy().to_string();
            let id = file_name
                .strip_suffix(".map")
                .unwrap_or(&file_name)
                .to_string();
            (id, path)
        })
        .collect();

    entries.sort_by(|left, right| left.0.cmp(&right.0));

    if entries.is_empty() {
        panic!("No map files found in {}", maps_dir.display());
    }

    let mut source = String::from("// @generated by build.rs — do not edit\n\n");
    source.push_str("pub static MAP_BLOBS: &[(&str, &str)] = &[\n");

    for (id, path) in &entries {
        let relative = path
            .strip_prefix(&manifest_dir)
            .unwrap_or(path)
            .display()
            .to_string()
            .replace('\\', "/");
        source.push_str(&format!(
            "    (\"{id}\", include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/{relative}\"))),\n"
        ));
    }

    source.push_str("];\n");
    fs::write(&out_path, source).expect("Failed to write maps_embedded.rs");

    println!("cargo:rerun-if-changed={}", maps_dir.display());
    for (_, path) in &entries {
        println!("cargo:rerun-if-changed={}", path.display());
    }

    tauri_build::build();
}
