// @generated by build.rs — do not edit

pub static MAP_BLOBS: &[(&str, &str)] = &[
    ("fork", include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/../content/maps/fork.map.json"))),
    ("midline", include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/../content/maps/midline.map.json"))),
    ("rings", include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/../content/maps/rings.map.json"))),
    ("split", include_str!(concat!(env!("CARGO_MANIFEST_DIR"), "/../content/maps/split.map.json"))),
];
